- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    # Shell stuff
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    # Git
    ~/.gitconfig: gitconfig

- shell:
  - [git submodule update --init --recursive, Installing submodules]
